### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by artamonJr** [alanreidt/slider#9]
Разнеси зависимости на devDep и dep
dependencies - зависимости без которых не может обойтись проект
devDependencies - зависимости без которых может обойтись проект
Пропиши скрипт для линтирования проекта

**Comment by alanreidt** [comment]
Готово.

**Comment by alanreidt** [comment]
Коммиты в перемешку вышли, но здесь, если что, изменения по главной ветке (код самого слайдера) и по gh-pages (код для демо страницы).

**Comment by madnessJs** [comment]
> Коммиты в перемешку вышли, но здесь, если что, изменения по главной ветке (код самого слайдера) и по gh-pages (код для демо страницы).

Не надо ничего разделять, делай на 1 изменение 1 коммит. В данном случае хватило бы 2-ух коммитов)

**Comment by madnessJs** [comment]
У тебя проект может существовать без parcel, sass и т.п., в данном случае?
![image](https://user-images.githubusercontent.com/46949445/76501939-36582c00-6454-11ea-92f2-ff1e7137a255.png)

**Comment by alanreidt** [comment]
> У тебя проект может существовать без parcel, sass и т.п., в данном случае?
> ![image](https://user-images.githubusercontent.com/46949445/76501939-36582c00-6454-11ea-92f2-ff1e7137a255.png)

Да, проект может работать без них в production версии (parcel только собирает проект; sass будет скомпилирован в css), они нужны только при разработке (development).

Ты неправильно понял предназначение этого разделения. Оно просто дает понять npm, какие зависимости требуется загрузить при тех или иных требования. Например, если ты скачал проект только для использования (production версия), то зависимости требуемые при разработке проекта npm скачивать не будет.

**Comment by madnessJs** [comment]
А какую роль играют эти зависимости в prod сборке?
![image](https://user-images.githubusercontent.com/46949445/76504757-60601d00-6459-11ea-8438-61176b9db871.png)

**Comment by alanreidt** [comment]
> А какую роль играют эти зависимости в prod сборке?
> ![image](https://user-images.githubusercontent.com/46949445/76504757-60601d00-6459-11ea-8438-61176b9db871.png)

@madnessJs Допустим, ты хочешь подключить мой слайдер через npm к своему проекту. Тогда, тебе нужен Lodash, так как он использован в Модели для написания кода в функциональном стиле. @bem-react/classname требуется для составления classNames для разметки и стилей слайдера. deep-equal я планирую использовать для сравнения объектов входящих опций для Модели с текущими и на основе этого производить оповещение о событии update. Но это пока я еще не реализовал.

**Comment by madnessJs** [comment]
> > А какую роль играют эти зависимости в prod сборке?
> > ![image](https://user-images.githubusercontent.com/46949445/76504757-60601d00-6459-11ea-8438-61176b9db871.png)
> 
> @madnessJs Допустим, ты хочешь подключить мой слайдер через npm к своему проекту. Тогда, тебе нужен Lodash, так как он использован в Модели для написания кода в функциональном стиле. @bem-react/classname требуется для составления classNames для разметки и стилей слайдера. deep-equal я планирую использовать для сравнения объектов входящих опций для Модели с текущими и на основе этого производить оповещение о событии update. Но это пока я еще не реализовал.

Сейчас понял, спасибо за объяснение. Т.е. когда я подключу твой проект как внешнюю зависимость у меня автоматически скачаются твои зависимости из depenencies?

**Comment by alanreidt** [comment]
@madnessJs Да. [npm документация](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file).

**Comment by madnessJs** [comment]
Нужно добавить private свойство и убрать main

**Comment by madnessJs** [comment]
Также убери keywords, version, description

**Comment by alanreidt** [comment]
Они опциональны. Я заполнил их, чтобы не были пустыми.

**Comment by alanreidt** [comment]
@madnessJs закрываю?

**Comment by madnessJs** [comment]
> @madnessJs закрываю?

все issues закрываю сам)

**Comment by madnessJs** [comment]
> @madnessJs
> Они опциональны. Я заполнил их, чтобы не были пустыми.

Какую роль они выполняют в твоем случае?

**Comment by alanreidt** [comment]
Прямую. Есть в планах опубликовать проект позже.

**Comment by madnessJs** [comment]
> @madnessJs
> Прямую. Есть в планах опубликовать проект позже.

Убери пока все поля кроме dep, devdep, scripts, private. Как соберешься выкладывать, добавишь

**Comment by alanreidt** [comment]
Ну а толку мне туда-сюда это все гонять, если оно никакого значения сейчас не имеет?

**Comment by artamonJr** [comment]
Господи) изучи тогда [эту](https://docs.npmjs.com/files/package.json) статью, раз тебе нужны на все веские аргументы)

**Comment by alanreidt** [comment]
Я по ней и ориентируюсь. Единственные необходимые поля — name и version, и то при публикации модуля. Все остальное по-желанию.

**Comment by artamonJr** [comment]
> Я по ней и ориентируюсь. Единственные необходимые поля — name и version, и то при публикации модуля. Все остальное по-желанию.

зачем ты тогда эти исправления внес?)
![image](https://user-images.githubusercontent.com/46949445/77755284-ff7e3a80-703d-11ea-8ce4-b6e7955adaf0.png)

**Comment by alanreidt** [comment]
Потому что main в рамках данного проекта совсем не нужен. А private полезен будет. Не пойму, что ты хочешь этим доказать.

**Comment by artamonJr** [comment]
> Потому что main в рамках данного проекта совсем не нужен. А private полезен будет. Не пойму, что ты хочешь этим доказать.

'main совсем не нужен'. А description, к примеру, нужен но не совсем?) main то ты убрал, а за другие поля горой стоишь, почему?)) Я не доказываю ничего, просто пытаюсь понять тебя по этому вопросу

**Comment by alanreidt** [comment]
@artamonJr
Main не подходит по своему предназначению. В документации оно немного расплывчато описано, но, в кратце, мне в проекте нужно поле browser использовать, так как есть зависимость от окружения браузера. То есть, main свойство, при любом раскладе лишнее. А другие поля понадобятся, когда нужно будет опубликовать проект.

**Comment by alanreidt** [comment]
Но я вижу теперь в чем проблема. Я так понимаю, что проверяющим толком не объясняли в чем их задачи на ревью?

Видишь ли, в рамках данной правки, ключевой задачей является проверить мое понимание базовых требований для package.json при работе с проектами (хотя я не уверен, что данные требования установлены внутри команды). А именно: scripts, поля связанные с окружением проекта (линтеры, тесты...), знание о существовании поля private (проекты в npm не публикуются), правильное разбиение зависимостей (важно даже в приватных проектах, так как позволяет установить только production зависимости при желании). Остальное не важно, если не стоит задачи публикации (в моем случае она присутствует).

**Comment by alanreidt** [comment]
И, по этой же причине, по остальным issues много чего лишнего происходит. Но это уже вопрос к Сергею.

**Comment by artamonJr** [comment]
Антон ты сам задал этот стиль общения, а сейчас, когда с тобой общаются в стиле твоего общения - ты не доволен) Ты пытаешься быть настолько умным, насколько ты сам себя видишь, но это может в некоторых случаях сыграть злую шутку(в этом). Ты даже знаешь, что входит в наши обязанности как ревьюиров) Может напишешь Сергею сразу, чтобы тебя так взяли в команду, без проверки? Тк ты все и так сам знаешь)

**Comment by artamonJr** [comment]
Нужно просто быть немного проще, а не бегать к кому-то за помощью, чтобы тебе помогли уладить вопросы

**Comment by alanreidt** [comment]
@artamonJr Давай без оскорблений. Я ни к кому за помощью не бегал, а уточнял возникший вопрос. Мне не понятно было откуда ты взял требования добавления доп. функциональности. Если в случае с зависимостями был абсолют — документация, то в случае с добавление доп. функциональности мог помочь только Сергей.

Я, по-правде, не вижу какой-либо направленности в твоих требованиях. Удаление, выше упомянутых, полей ничего совершенно не изменит (кроме того, что мне потребуется позже добавить их обратно). Поэтому, я и заключаю, что задачи у вас не поставлены, либо очень свободны.

А свое видение задач по данной правке (и в общем) легко установить логически, исходя из целей заданий данной программы.

**Comment by artamonJr** [comment]
@alanreidt Хорошо, закрыли эти принципиальные моменты. Задачи у нас можно сказать свободны в целом, да. Руководствуемся только своим опытом и best practices компании. Согласен с тобой, возможно я пытался подвести тебя под свои рамки и не учитывал, что люди по-разному смотрят на вещи) Будет круто, если будешь отписываться в телеграмме, как можно проверять
